apiVersion: v1
kind: Pod
metadata:
  name:  nginx-pod
spec:
  containers:
    - name:  web
      image: nginx:latest
      ports:  
        - name: http
          containerPort: 80
          protocol: TCP