apiVersion: v1
kind: Pod
metadata:
  name:  nginx-pod
spec:
  containers:
    - name:  web
      image: nginx:latest
      ports:  
        - name: http
          containerPort: 80
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
    name: nginxSVC
spec:
    type: NodePort
    ports:
    - name:  HTTP
      port: 80
      nodePort: 30000   
      targetPort: 80
    selector:
      app: nginx-pod
